[package]
name = "BevySim"
version = "0.1.0"
edition = "2021"

[dependencies]
rand="0.8.5"
bevy="0.13.2"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lib]
name = "physics"
path = "src/physics/mod.rs"